name: Artifact
description: Store build artifacts and documentation
inputs:
  output-dir:
    description: Directory to store artifacts
    required: false
    default: artifacts
  doc-filename:
    description: Filename for the documentation archive
    required: true
runs:
  using: composite
  steps:
    - name: Generate Packages
      run: |
        echo "::group::dotnet pack"
        dotnet pack --no-build -c Release -o "${OUTPUT_PATH}"
        echo "::endgroup::"
      shell: bash
      env:
        OUTPUT_PATH: ${{ github.workspace }}/${{ inputs.output-dir }}

    - name: Install docfx
      run: |
        echo "::group::dotnet tool install"
        dotnet tool install -g docfx
        echo "::endgroup::"
      shell: bash

    - name: Generate Documentations
      run: |
        echo "::group::docfx"
        docfx doc/docfx.json
        echo "::endgroup::"
      shell: bash

    - name: Archive Documentations
      run: |
        echo "::group::tar"
        tar -zcf "${DOC_FILE_PATH}" -- *
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ github.workspace }}/doc/_site
      env:
        DOC_FILE_PATH: ${{ github.workspace }}/${{ inputs.output-dir }}/${{ inputs.doc-filename }}
