name: Artifact
description: Store build artifacts and documentation
inputs:
  repository-name:
    description: Name of the repository
    required: true
  output-dir:
    description: Directory to store artifacts
    required: false
    default: artifacts
  doc-filename:
    description: Filename for the documentation archive
    required: true
runs:
  using: composite
  steps:
    - name: Generate Packages
      run: |
        Write-Output "::group::uv build"
        uv build -o "${env:OUTPUT_PATH}"
        Write-Output "::endgroup::"
      shell: pwsh
      env:
        OUTPUT_PATH: ${{ github.workspace }}\${{ inputs.output-dir }}

    - name: Install Libraries
      run: |
        Write-Output "::group::uv sync"
        uv sync --group doc
        Write-Output "::endgroup::"
      shell: pwsh

    - name: Generate API Documentations
      id: api
      run: |
        Write-Output "::group::uv run sphinx-apidoc"
        $OUTPUT_DIR = Join-Path -Path ([IO.Path]::GetTempPath()) -ChildPath (New-Guid)
        mkdir -p "${OUTPUT_DIR}"
        Write-Output "doc_path=${OUTPUT_DIR}" >> "${env:GITHUB_OUTPUT}"

        uv run sphinx-apidoc -F -f -a -H "${env:REPOSITORY_NAME}" -A "${env:GITHUB_REPOSITORY_OWNER}" -V latest -o "${OUTPUT_DIR}" src
        Write-Output "::endgroup::"
      shell: pwsh
      env:
        REPOSITORY_NAME: ${{ inputs.repository-name }}

    - name: Generate Documentations
      run: |
        Write-Output "::group::uv run make"
        uv run .\make.bat html
        Write-Output "::endgroup::"
      shell: pwsh
      working-directory: ${{ steps.api.outputs.doc_path }}
      env:
        UV_PROJECT: ${{ github.workspace }}

    - name: Archive Documentations
      run: |
        Write-Output "::group::zip"
        Compress-Archive -Path '*' -DestinationPath "${env:DOC_FILE_PATH}"
        Write-Output "::endgroup::"
      shell: pwsh
      working-directory: ${{ steps.api.outputs.doc_path }}\_build\html
      env:
        DOC_FILE_PATH: ${{ github.workspace }}\${{ inputs.output-dir }}\${{ inputs.doc-filename }}
