name: Initialize Environments
description: Initialize the Redmine environments.
inputs:
  working-directory:
    description: The working directory to run.
    required: true
runs:
  using: composite
  steps:
    - name: Initialize Environments
      run: |
        echo "::group::initialize environments"
        bundle exec rake db:drop
        bundle exec rake db:create db:migrate redmine:plugins:migrate
        echo ja | bundle exec rake redmine:load_default_data
        echo "::endgroup::"

        bundle exec rails about
      shell: bash
      working-directory: ${{ inputs.working-directory }}
