name: Setup
description: Setup the environment for the repository.
outputs:
  repository-name:
    description: The name of the repository
    value: ${{ steps.repository.outputs.name }}
  rust-target:
    description: The Rust target architecture and version
    value: ${{ steps.repository.outputs.rust_target }}
runs:
  using: composite
  steps:
    - name: Setup Repository Information
      id: repository
      run: |
        Write-Output "::group::setup repository information"
        mkdir -p .\artifacts
        $REPOSITORY_NAME = ${env:GITHUB_REPOSITORY}.split("/")[-1]
        Write-Output "name=${REPOSITORY_NAME}" >> "${env:GITHUB_OUTPUT}"
        $RUST_VERSION = $(rustc --version).split(' ')[1]
        $RUST_TARGET = "$(rustc --print host-tuple)-${RUST_VERSION}"
        Write-Output "rust_target=${RUST_TARGET}" >> "${env:GITHUB_OUTPUT}"
        Write-Output "::endgroup::"
      shell: pwsh
