name: Setup Plugin
description: Setup the plugin in the Redmine environment.
inputs:
  working-directory:
    description: The working directory to run.
    required: true
  plugin-name:
    description: The name of the plugin.
    required: true
runs:
  using: composite
  steps:
    - name: Install Essentials
      run: |
        echo "::group::apt-get"
        apt-get update -y
        apt-get install -y \
            build-essential \
            curl \
            unzip
        echo "::endgroup::"
      shell: bash

    - name: Install Plugin
      run: |
        echo "::group::install plugin"
        ln -s "${PLUGIN_DIR}" "${PLUGIN_NAME}"
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}/plugins
      env:
        PLUGIN_DIR: ${{ github.workspace }}
        PLUGIN_NAME: ${{ inputs.plugin-name }}

    - name: Install Dependencies
      run: |
        echo "::group::bundle install"
        bundle install --with test
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
