name: Test
description: Run test and report coverages
inputs:
  output-dir:
    description: Directory to store coverage reports
    required: false
    default: artifacts
runs:
  using: composite
  steps:
    - name: Install Libraries
      run: |
        echo "::group::uv sync"
        uv sync --group test
        echo "::endgroup::"
      shell: bash

    - name: Run Tests
      run: |
        echo "::group::uv run tox"
        uv run tox
        echo "::endgroup::"
      shell: bash

    - name: Generate Coverage Summary Report
      run: |
        echo "::group::uv run coverage report"
        uv run coverage report > "${OUTPUT_PATH}/Summary.txt"
        uv run coverage report --format=markdown > "${OUTPUT_PATH}/SummaryGithub.md"
        echo "::endgroup::"

        cat "${OUTPUT_PATH}/Summary.txt"
        cat "${OUTPUT_PATH}/SummaryGithub.md" > "${GITHUB_STEP_SUMMARY}"
      shell: bash
      env:
        OUTPUT_PATH: ${{ github.workspace }}/${{ inputs.output-dir }}

    - name: Generate Coverage HTML Report
      id: html
      run: |
        echo "::group::uv run coverage html"
        OUTPUT_DIR=$(mktemp -d)
        echo "coverage_path=${OUTPUT_DIR}" >> "${GITHUB_OUTPUT}"

        uv run coverage html --directory="${OUTPUT_DIR}"
        echo "::endgroup::"
      shell: bash

    - name: Archive Coverage HTML Report
      run: |
        echo "::group::tar"
        tar -zcf "${DOC_FILE_PATH}" -- *
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ steps.html.outputs.coverage_path }}
      env:
        DOC_FILE_PATH: ${{ github.workspace }}/${{ inputs.output-dir }}/coverage.tar.gz
