name: Static Analysis
description: Run static analysis tools
inputs:
  enable-lint:
    description: Whether to enable linting (1 to enable, 0 to disable)
    required: false
    default: 1
runs:
  using: composite
  steps:
    - name: Check Format
      run: |
        echo "::group::go fmt"
        go fmt ./...
        echo "::endgroup::"

        git diff --exit-code --quiet
      shell: bash

    - name: Check Lint
      if: ${{ inputs.enable-lint != '0' }}
      run: |
        echo "::group::go tool staticcheck"
        go tool staticcheck ./...
        echo "::endgroup::"
      shell: bash
