name: Static Analysis
description: Run static analysis tools
inputs:
  enable-lint:
    description: Whether to enable linting (1 to enable, 0 to disable)
    required: false
    default: 1
  working-directory:
    description: Directory to work
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Format
      run: |
        echo "::group::cargo fmt"
        cargo fmt --all --check
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Check Lint
      if: ${{ inputs.enable-lint != '0' }}
      run: |
        echo "::group::cargo clippy"
        cargo clippy --fix
        echo "::endgroup::"

        git diff --exit-code --quiet
      shell: bash
      working-directory: ${{ inputs.working-directory }}
