name: Setup
description: Setup the environment for the repository.
outputs:
  repository-name:
    description: The name of the repository
    value: ${{ steps.repository.outputs.name }}
runs:
  using: composite
  steps:
    - name: Setup Repository Information
      id: repository
      run: |
        echo "::group::setup repository information"
        mkdir -p ./artifacts
        echo "name=${GITHUB_REPOSITORY#"${GITHUB_REPOSITORY_OWNER}/"}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash

    - name: Install Project Management Tool
      run: |
        echo "::group::pip install uv"
        pip install uv
        echo "::endgroup::"
      shell: bash
