name: Go Release Windows

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v5

    - name: Setup
      id: setup
      uses: 9506hqwy/actions/go/setup-pwsh@main

    - name: Generate Artifact
      uses: 9506hqwy/actions/go/artifact-pwsh@main
      with:
        configuration: Release
        output-dir: artifacts

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.setup.outputs.repository-name }}-${{ github.workflow }}-${{ steps.setup.outputs.go-target }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
