name: Rust Release Windows

on:
  workflow_call:
    inputs:
      use-submodules:
        description: Whether to use submodules
        default: false
        required: false
        type: boolean

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v5
      with:
        submodules: ${{ inputs.use-submodules }}

    - name: Setup
      id: setup
      uses: 9506hqwy/actions/rust/setup-pwsh@main

    - name: Generate Artifact
      uses: 9506hqwy/actions/rust/artifact-pwsh@main
      with:
        configuration: Release
        output-dir: artifacts
        doc-filename: help-${{ steps.setup.outputs.rust-target }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.setup.outputs.repository-name }}-${{ github.workflow }}-${{ steps.setup.outputs.rust-target }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
